# Generated by Django 6.0.3 on 2026-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("poster_image", models.ImageField(upload_to="movies/posters/")),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="movies/banners/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("genres", models.ManyToManyField(to="core.genre")),
            ],
        ),
    ]
